// Code generated by github.com/vektah/dataloaden, DO NOT EDIT.

package cli

import (
	"sync"
	"time"
)

// BlockLoaderConfig captures the config to create a new BlockLoader
type BlockLoaderConfig struct {
	// Fetch is a method that provides the data for the loader
	Fetch func(keys []uint64) ([]Block, []error)

	// Wait is how long wait before sending a batch
	Wait time.Duration

	// MaxBatch will limit the maximum number of keys to send in one batch, 0 = not limit
	MaxBatch int
}

// NewBlockLoader creates a new BlockLoader given a fetch, wait, and maxBatch
func NewBlockLoader(config BlockLoaderConfig) *BlockLoader {
	return &BlockLoader{
		fetch:    config.Fetch,
		wait:     config.Wait,
		maxBatch: config.MaxBatch,
	}
}

// BlockLoader batches and caches requests
type BlockLoader struct {
	// this method provides the data for the loader
	fetch func(keys []uint64) ([]Block, []error)

	// how long to done before sending a batch
	wait time.Duration

	// this will limit the maximum number of keys to send in one batch, 0 = no limit
	maxBatch int

	// INTERNAL

	// lazily created cache
	cache map[uint64]Block

	// the current batch. keys will continue to be collected until timeout is hit,
	// then everything will be sent to the fetch method and out to the listeners
	batch *blockLoaderBatch

	// mutex to prevent races
	mu sync.Mutex
}

type blockLoaderBatch struct {
	keys    []uint64
	data    []Block
	error   []error
	closing bool
	done    chan struct{}
}

// Load a Block by key, batching and caching will be applied automatically
func (l *BlockLoader) Load(key uint64) (Block, error) {
	return l.LoadThunk(key)()
}

// LoadThunk returns a function that when called will block waiting for a Block.
// This method should be used if you want one goroutine to make requests to many
// different data loaders without blocking until the thunk is called.
func (l *BlockLoader) LoadThunk(key uint64) func() (Block, error) {
	l.mu.Lock()
	if it, ok := l.cache[key]; ok {
		l.mu.Unlock()
		return func() (Block, error) {
			return it, nil
		}
	}
	if l.batch == nil {
		l.batch = &blockLoaderBatch{done: make(chan struct{})}
	}
	batch := l.batch
	pos := batch.keyIndex(l, key)
	l.mu.Unlock()

	return func() (Block, error) {
		<-batch.done

		var data Block
		if pos < len(batch.data) {
			data = batch.data[pos]
		}

		var err error
		// its convenient to be able to return a single error for everything
		if len(batch.error) == 1 {
			err = batch.error[0]
		} else if batch.error != nil {
			err = batch.error[pos]
		}

		if err == nil {
			l.mu.Lock()
			l.unsafeSet(key, data)
			l.mu.Unlock()
		}

		return data, err
	}
}

// LoadAll fetches many keys at once. It will be broken into appropriate sized
// sub batches depending on how the loader is configured
func (l *BlockLoader) LoadAll(keys []uint64) ([]Block, []error) {
	results := make([]func() (Block, error), len(keys))

	for i, key := range keys {
		results[i] = l.LoadThunk(key)
	}

	blocks := make([]Block, len(keys))
	errors := make([]error, len(keys))
	for i, thunk := range results {
		blocks[i], errors[i] = thunk()
	}
	return blocks, errors
}

// LoadAllThunk returns a function that when called will block waiting for a Blocks.
// This method should be used if you want one goroutine to make requests to many
// different data loaders without blocking until the thunk is called.
func (l *BlockLoader) LoadAllThunk(keys []uint64) func() ([]Block, []error) {
	results := make([]func() (Block, error), len(keys))
	for i, key := range keys {
		results[i] = l.LoadThunk(key)
	}
	return func() ([]Block, []error) {
		blocks := make([]Block, len(keys))
		errors := make([]error, len(keys))
		for i, thunk := range results {
			blocks[i], errors[i] = thunk()
		}
		return blocks, errors
	}
}

// Prime the cache with the provided key and value. If the key already exists, no change is made
// and false is returned.
// (To forcefully prime the cache, clear the key first with loader.clear(key).prime(key, value).)
func (l *BlockLoader) Prime(key uint64, value Block) bool {
	l.mu.Lock()
	var found bool
	if _, found = l.cache[key]; !found {
		l.unsafeSet(key, value)
	}
	l.mu.Unlock()
	return !found
}

// Clear the value at key from the cache, if it exists
func (l *BlockLoader) Clear(key uint64) {
	l.mu.Lock()
	delete(l.cache, key)
	l.mu.Unlock()
}

func (l *BlockLoader) unsafeSet(key uint64, value Block) {
	if l.cache == nil {
		l.cache = map[uint64]Block{}
	}
	l.cache[key] = value
}

// keyIndex will return the location of the key in the batch, if its not found
// it will add the key to the batch
func (b *blockLoaderBatch) keyIndex(l *BlockLoader, key uint64) int {
	for i, existingKey := range b.keys {
		if key == existingKey {
			return i
		}
	}

	pos := len(b.keys)
	b.keys = append(b.keys, key)
	if pos == 0 {
		go b.startTimer(l)
	}

	if l.maxBatch != 0 && pos >= l.maxBatch-1 {
		if !b.closing {
			b.closing = true
			l.batch = nil
			go b.end(l)
		}
	}

	return pos
}

func (b *blockLoaderBatch) startTimer(l *BlockLoader) {
	time.Sleep(l.wait)
	l.mu.Lock()

	// we must have hit a batch limit and are already finalizing this batch
	if b.closing {
		l.mu.Unlock()
		return
	}

	l.batch = nil
	l.mu.Unlock()

	b.end(l)
}

func (b *blockLoaderBatch) end(l *BlockLoader) {
	b.data, b.error = l.fetch(b.keys)
	close(b.done)
}
